# See http://www.appveyor.com/docs/appveyor-yml for reference

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\build.ps1 -pack

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: artifacts/*

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# we run tests explicitly as part of the build script
test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: Y4NUwAvYgYtcbINdDt3gWjeKKXYMjw2AU1dIRLC4TvroVT46afylm3fIrHZ0Tf6N
    artifact: artifacts/*
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

  # MyGet
  - provider: NuGet
    server: https://www.myget.org/F/nfig/api/v2/package
    symbol_server: https://www.myget.org/F/nfig/symbols/api/v2/package
    api_key:
      secure: 75kfQhijF72yzBF6A52uS7bdmHkTSwhUjbbQDBRfp2p41ALHa694NrodnIglIHPL
    artifact: /artifacts/.*\.nupkg/
    skip_symbols: false
    on:
      branch: master

  # NuGet.org
  - provider: NuGet
    api_key:
      secure: 0mIymJ7rdtMSl8ZBhx1laE3yQgQq+IUiSUpBtE9PJ3ujbW/lutCMxmsbEvK0dgAW
    artifact: /artifacts/.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true

